# Generated by Django 4.1.6 on 2023-02-11 14:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('batch_number', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhkmnrstuvwxz123456789_', length=16, max_length=16, prefix='b_')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='batch_qr_codes')),
                ('qr_pointer', models.CharField(blank=True, max_length=300, null=True, unique=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Jar', 'Jar'), ('Squeeze Bottle', 'Squeeze Bottle'), ('Pail', 'Pail')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('Clear', 'Clear'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Dark Brown', 'Dark Brown'), ('White', 'White')], max_length=20)),
                ('last_updated', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=10, null=True)),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('suburb', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, choices=[('ACT', 'Australian Capital Territory'), ('NSW', 'New South Wales'), ('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('WA', 'Western Australia')], max_length=3, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('post_code', models.CharField(max_length=4)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='e-mail')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhkmnrstuvwxz123456789_', length=16, max_length=16, prefix='so_')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('payment_term', models.CharField(choices=[('Immediate', 'Immediate'), ('30 Days', '30 Days')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='supplier_order_qr_codes')),
                ('qr_pointer', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.customer')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='HoneyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Lid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Jar Lid', 'Jar Lid'), ('Squeeze Lid', 'Squeeze Lid'), ('Squeeze Tip', 'Squeeze Tip'), ('Pail Lid', 'Pail Lid')], max_length=20)),
                ('quantity', models.IntegerField(default=0)),
                ('color', models.CharField(choices=[('Clear', 'Clear'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Dark Brown', 'Dark Brown'), ('White', 'White')], max_length=20)),
                ('last_updated', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pallet_number', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('capacity_cartons', models.IntegerField(default=0)),
                ('layout', models.FileField(blank=True, null=True, upload_to='pallet_layouts/')),
                ('last_updated', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('supplier_number', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=10, null=True)),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('suburb', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(choices=[('ACT', 'Australian Capital Territory'), ('NSW', 'New South Wales'), ('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('WA', 'Western Australia')], max_length=3)),
                ('post_code', models.CharField(max_length=4)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('abn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ABN')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='e-mail')),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bsb', models.CharField(blank=True, max_length=100, null=True, verbose_name='BSB')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TopInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhkmnrstuvwxz123456789_', length=16, max_length=16, prefix='so_')),
                ('gross_total_weight', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Gross Weight')),
                ('ibc_total_weight', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='IBC/Drum Weight')),
                ('net_total_weight', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('honey_levy', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('payment_term', models.CharField(choices=[('Immediate', 'Immediate'), ('30 Days', '30 Days')], max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='supplier_order_qr_codes')),
                ('qr_pointer', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.supplier')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_date', models.DateField(default=django.utils.timezone.now)),
                ('production_code', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhkmnrstuvwxz123456789_', length=16, max_length=16, prefix='p_')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bottle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('units_made', models.PositiveIntegerField(null=True)),
                ('units_requested', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Paused', 'Paused'), ('Complete', 'Complete')], default='New', max_length=20)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='production_images')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.brand')),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.carton')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.container')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.label')),
                ('lid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.lid')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='home.customerorder')),
                ('pallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.pallet')),
                ('top_insert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.topinsert')),
            ],
        ),
        migrations.CreateModel(
            name='HoneyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhkmnrstuvwxz123456789_', length=16, max_length=16, prefix='h_')),
                ('ibc_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('nova_ibc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nova IBC')),
                ('supplier_ibc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier IBC')),
                ('date_received', models.DateField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='home.batch')),
                ('honey_types', models.ManyToManyField(to='home.honeytype')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honey_stock', to='home.supplierorder')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='home.production'),
        ),
    ]
