# Generated by Django 4.1.5 on 2023-01-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beekeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('suppliernum', models.CharField(max_length=100, null=True)),
                ('ibc', models.CharField(max_length=100, null=True)),
                ('unitnumber', models.CharField(max_length=10, null=True)),
                ('streetnumber', models.CharField(max_length=10, null=True)),
                ('addressline_1', models.CharField(max_length=100, null=True)),
                ('addressline_2', models.CharField(max_length=100, null=True)),
                ('suburb', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(choices=[('ACT', 'ACT'), ('NSW', 'NSW'), ('NT', 'NT'), ('QLD', 'QLD'), ('SA', 'SA'), ('TAS', 'TAS'), ('VIC', 'VIC'), ('WA', 'WA')], max_length=3)),
                ('postcode', models.CharField(max_length=4)),
                ('contactnumber', models.CharField(max_length=20, null=True)),
                ('abn', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
