# Generated by Django 4.1.6 on 2023-02-09 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beekeeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('supplier_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ibc_identification', models.CharField(blank=True, max_length=100, null=True, verbose_name='IBC identification')),
                ('unit_number', models.CharField(blank=True, max_length=10, null=True)),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('suburb', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(choices=[('ACT', 'ACT'), ('NSW', 'NSW'), ('NT', 'NT'), ('QLD', 'QLD'), ('SA', 'SA'), ('TAS', 'TAS'), ('VIC', 'VIC'), ('WA', 'WA')], max_length=3)),
                ('post_code', models.CharField(max_length=4)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('abn', models.CharField(blank=True, max_length=100, null=True, verbose_name='ABN')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='e-mail')),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bsb', models.CharField(blank=True, max_length=100, null=True, verbose_name='BSB')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HoneyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('gross_total_weight', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Gross Weight')),
                ('ibc_total_weight', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='IBC/Drum Weight')),
                ('net_weight', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('honey_levy', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('payment_term', models.CharField(choices=[('Immediate', 'Immediate'), ('30 Days', '30 Days')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='order_qr_codes')),
                ('qr_pointer', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('bee_keeper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.beekeeper')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibc_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('gross_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('nv_ibc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nova IBC')),
                ('used', models.BooleanField(default=False)),
                ('honey_types', models.ManyToManyField(to='home.honeytype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='home.order')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(default=datetime.date(2028, 2, 8))),
                ('batch_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bottle_type', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_weight', models.IntegerField(default=0)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_made', models.PositiveIntegerField(null=True)),
                ('max_possible', models.PositiveIntegerField(blank=True, null=True)),
                ('batch_status', models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Complete', 'Complete')], default='New', max_length=20)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='batch_qr_codes')),
                ('qr_pointer', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('source_containers', models.ManyToManyField(to='home.orderitem')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
