# Generated by Django 4.1.5 on 2023-01-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beekeeper',
            old_name='addressline_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='beekeeper',
            old_name='addressline_2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='beekeeper',
            old_name='contactnumber',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='beekeeper',
            old_name='postcode',
            new_name='post_code',
        ),
        migrations.RenameField(
            model_name='beekeeper',
            old_name='streetnumber',
            new_name='street_number',
        ),
        migrations.RenameField(
            model_name='beekeeper',
            old_name='ibc',
            new_name='supplier_name',
        ),
        migrations.RenameField(
            model_name='beekeeper',
            old_name='name',
            new_name='supplier_number',
        ),
        migrations.RenameField(
            model_name='beekeeper',
            old_name='unitnumber',
            new_name='unit_number',
        ),
        migrations.RemoveField(
            model_name='beekeeper',
            name='suppliernum',
        ),
        migrations.AddField(
            model_name='beekeeper',
            name='ibc_identification',
            field=models.CharField(max_length=100, null=True, verbose_name='IBC identification'),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='abn',
            field=models.CharField(max_length=100, verbose_name='ABN'),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='e-mail'),
        ),
    ]
