# Generated by Django 4.1.6 on 2023-02-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_pallet_dimensions_pallet_height_pallet_width'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pallet',
            old_name='height',
            new_name='length',
        ),
    ]
