# Generated by Django 4.1.5 on 2023-01-09 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Mallee', 'Mallee'), ('Blue Gum', 'Blue Gum'), ('Canola', 'Canola'), ('Salvation Jane', 'Salvation Jane'), ('Red Gum', 'Red Gum'), ('Mix Flora', 'Mix Flora')], max_length=50)),
                ('weight', models.PositiveIntegerField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.order')),
            ],
        ),
    ]
