# Generated by Django 4.1.6 on 2023-02-12 16:32

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_height_pallet_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='total_weight_price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='honeystock',
            name='stock_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhkmnrstuvwxz123456789', length=16, max_length=16, prefix='h_'),
        ),
    ]
