# Generated by Django 4.1.6 on 2023-02-12 16:51

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_supplierorder_total_weight_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhkmnrstuvwxz123456789', length=16, max_length=16, prefix='b_'),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='order_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhkmnrstuvwxz123456789', length=16, max_length=16, prefix='so_'),
        ),
    ]
