# Generated by Django 4.1.5 on 2023-01-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beekeeper',
            name='abn',
            field=models.CharField(blank=True, max_length=100, verbose_name='ABN'),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='ibc_identification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IBC identification'),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='street_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='suburb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='supplier_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='unit_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
