# Generated by Django 4.1.5 on 2023-01-09 10:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_beekeeper_abn_alter_beekeeper_address_line_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_weight',
            new_name='gross_total_weight',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='weight',
            new_name='gross_weight',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='immediate_payment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='home.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.honey'),
        ),
    ]
