# Generated by Django 4.1.6 on 2023-02-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_batch_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_status',
            field=models.CharField(choices=[('New', 'New'), ('In Production', 'In Production'), ('Used', 'Used')], default='New', max_length=20),
        ),
    ]
