# Generated by Django 4.1.6 on 2023-02-13 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_batch_batch_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='production',
        ),
        migrations.AddField(
            model_name='production',
            name='production',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='home.batch'),
        ),
        migrations.AlterField(
            model_name='honeystock',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='honey_stock', to='home.batch'),
        ),
    ]
