# Generated by Django 4.1.5 on 2023-01-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order_unit_price_alter_order_gross_total_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='gross_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
