# Generated by Django 4.1.5 on 2023-01-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_orderitem_gross_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beekeeper',
            options={'ordering': ('supplier_name',)},
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='supplier_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='bee_keeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.beekeeper'),
        ),
    ]
