# Generated by Django 4.1.6 on 2023-02-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_batch_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honeystock',
            name='batch',
        ),
        migrations.AddField(
            model_name='batch',
            name='honey_stock',
            field=models.ManyToManyField(to='home.honeystock'),
        ),
    ]
