# Generated by Django 4.1.6 on 2023-02-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_production_bottle_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topinsert',
            name='dimensions',
        ),
        migrations.AddField(
            model_name='label',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='topinsert',
            name='length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topinsert',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
