# Generated by Django 4.1.5 on 2023-01-10 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='beekeeper',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beekeeper',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='beekeeper',
            name='bsb',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BSB'),
        ),
        migrations.AlterField(
            model_name='beekeeper',
            name='abn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ABN'),
        ),
        migrations.CreateModel(
            name='HoneyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='honey_order_item', to='home.orderitem')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.honey')),
            ],
        ),
    ]
