# Generated by Django 4.1.6 on 2023-02-16 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_topinsert_dimensions_label_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='product_name',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.brand')),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.product'),
        ),
        migrations.AddField(
            model_name='production',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.product'),
        ),
    ]
