# Generated by Django 4.1.5 on 2023-01-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_beekeeper_account_name_beekeeper_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ibc_weight',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='type',
        ),
        migrations.AddField(
            model_name='order',
            name='ibc_total_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ibc_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
