# Generated by Django 4.1.6 on 2023-02-16 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_production_product_name_product_label_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.product'),
        ),
    ]
