# Generated by Django 4.1.5 on 2023-01-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_order_ibc_weight_remove_orderitem_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gross_total_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Gross Weight'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ibc_total_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='IBC/Drum Weight'),
        ),
    ]
