# Generated by Django 4.1.5 on 2023-01-11 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_order_gross_total_weight_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Honey',
            new_name='HoneyType',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order', to='home.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='type',
            field=models.ManyToManyField(related_name='order_item', to='home.honeytype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bee_keeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.beekeeper'),
        ),
        migrations.DeleteModel(
            name='HoneyOrderItem',
        ),
    ]
