# Generated by Django 4.1.6 on 2023-02-16 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_customerorder_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='label',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='label',
            name='container_type',
        ),
        migrations.RemoveField(
            model_name='label',
            name='product',
        ),
        migrations.RemoveField(
            model_name='lid',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='lid',
            name='container_type',
        ),
        migrations.RemoveField(
            model_name='production',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='production',
            name='carton',
        ),
        migrations.RemoveField(
            model_name='production',
            name='container',
        ),
        migrations.RemoveField(
            model_name='production',
            name='label',
        ),
        migrations.RemoveField(
            model_name='production',
            name='lid',
        ),
        migrations.AddField(
            model_name='product',
            name='carton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.carton'),
        ),
        migrations.AddField(
            model_name='product',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.container'),
        ),
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.label'),
        ),
        migrations.AddField(
            model_name='product',
            name='lid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.lid'),
        ),
    ]
