# Generated by Django 4.1.6 on 2023-02-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_container_brand_remove_label_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='total_weight',
        ),
        migrations.RemoveField(
            model_name='production',
            name='units_requested',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='units_requested',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_weight',
            field=models.IntegerField(default=0),
        ),
    ]
