# Generated by Django 4.1.5 on 2023-01-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_honey_honeytype_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='immediate_payment',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_term',
            field=models.CharField(choices=[('Immediate', 'Immediate'), ('30 Days', '30 Days')], max_length=20, null=True),
        ),
    ]
