# Generated by Django 4.1.6 on 2023-02-16 03:14

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_production_total_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='units_requested',
        ),
        migrations.RemoveField(
            model_name='production',
            name='order',
        ),
        migrations.RemoveField(
            model_name='production',
            name='product',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='total_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='order_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhkmnrstuvwxz123456789_', length=16, max_length=16, prefix='co_'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='customer_order_qr_codes'),
        ),
        migrations.CreateModel(
            name='CustomerOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_item_number', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefhkmnrstuvwxz123456789', length=12, max_length=12, prefix='oi_')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sub_total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='home.customerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.product')),
            ],
        ),
        migrations.AddField(
            model_name='production',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_item', to='home.customerorderitems'),
        ),
    ]
