# Generated by Django 4.1.5 on 2023-01-12 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_order_immediate_payment_order_payment_term'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='honey_types',
            field=models.ManyToManyField(to='home.honeytype'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='home.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bee_keeper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.beekeeper'),
            preserve_default=False,
        ),
    ]
