# Generated by Django 4.1.6 on 2023-02-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_customerorder_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='requested_units',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='production',
            name='units_made',
            field=models.IntegerField(default=0),
        ),
    ]
