# Generated by Django 4.1.6 on 2023-02-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_production_requested_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='container_images'),
        ),
        migrations.AddField(
            model_name='label',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='label_images'),
        ),
        migrations.AddField(
            model_name='lid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lid_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
