# Generated by Django 4.1.6 on 2023-02-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_container_image_label_image_lid_image_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerOrderItems',
            new_name='CustomerOrderItem',
        ),
        migrations.RemoveField(
            model_name='customerorder',
            name='product_name',
        ),
        migrations.AddField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Production', 'In Production'), ('Ready to Ship', 'Ready to Ship'), ('Shipped', 'Shipped')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='payment_term',
            field=models.CharField(choices=[('50% Deposit', '50% Deposit'), ('Full Payment', 'Full Payment'), ('Lead Time', 'Lead Time')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='layout',
            field=models.FileField(blank=True, null=True, upload_to='pallet_layouts'),
        ),
    ]
