# Generated by Django 4.1.6 on 2023-03-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_customerorderitems_customerorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carton',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='carton_images'),
        ),
    ]
