# Generated by Django 4.1.5 on 2023-01-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qrcode',
            field=models.ImageField(null=True, upload_to='order_qr_codes'),
        ),
    ]
