# Generated by Django 4.1.6 on 2023-03-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_carton_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carton',
            name='brand',
        ),
        migrations.AddField(
            model_name='label',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.brand'),
        ),
    ]
