# Generated by Django 4.1.5 on 2023-01-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_order_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qrcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
