# Generated by Django 4.2.3 on 2023-07-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_remove_carton_brand_label_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honeystock',
            name='supplier_ibc',
        ),
        migrations.AddField(
            model_name='supplier',
            name='ibc_identification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
