# Generated by Django 4.1.5 on 2023-01-13 21:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_order_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='net_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='nv_ibc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nova IBC'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('batch_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('containers', models.ManyToManyField(to='home.orderitem')),
            ],
        ),
    ]
