# Generated by Django 4.2.3 on 2023-08-04 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_honeystock_supplier_ibc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='order_item',
        ),
        migrations.AddField(
            model_name='production',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.customer'),
        ),
    ]
