# Generated by Django 4.2.3 on 2023-08-04 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_production_order_item_production_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.product'),
        ),
    ]
