# Generated by Django 4.1.5 on 2023-02-06 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_containers_batch_source_containers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='batch',
            name='unit_weight',
        ),
        migrations.AddField(
            model_name='batch',
            name='qrcode_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='qrcode_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Complete', 'Complete')], default='New', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='unit_weight_grams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='used',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2028, 2, 5)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='max_possible',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
