# Generated by Django 4.1.5 on 2023-02-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_batch_options_remove_batch_unit_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='date',
            new_name='batch_date',
        ),
        migrations.AddField(
            model_name='batch',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
