# Generated by Django 4.2.3 on 2023-08-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_production_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='honey_type',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
