# Generated by Django 4.2.3 on 2023-08-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_batch_tank_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='packed_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='previous_batch',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='remaining_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
