# Generated by Django 4.1.5 on 2023-02-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_rename_unit_weight_grams_batch_unit_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Processing', 'Processing'), ('Complete', 'Complete')], default='New', max_length=20),
        ),
    ]
