# Generated by Django 4.1.5 on 2023-02-07 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_orderitem_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2028, 2, 6)),
        ),
    ]
