# Generated by Django 4.2.3 on 2023-08-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_batch_previous_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='previous_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_batch', to='home.batch'),
        ),
    ]
