# Generated by Django 4.1.6 on 2023-08-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_batch_previous_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='label',
            name='color',
        ),
    ]
