# Generated by Django 4.1.5 on 2023-02-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_batch_expiry_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='status',
            new_name='batch_status',
        ),
    ]
