# Generated by Django 4.1.6 on 2023-08-25 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_product_brand_alter_product_carton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='top_insert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.topinsert'),
        ),
    ]
