# Generated by Django 4.1.5 on 2023-02-09 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_status_batch_batch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_pointer',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2028, 2, 8)),
        ),
        migrations.AlterField(
            model_name='order',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='order_qr_codes'),
        ),
    ]
