# Generated by Django 4.1.6 on 2023-08-25 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_production_top_insert'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.brand'),
        ),
        migrations.AlterField(
            model_name='container',
            name='type',
            field=models.CharField(choices=[('Jar', 'Jar'), ('Squeeze Bottle', 'Squeeze Bottle'), ('Pail', 'Pail'), ('Tub', 'Tub')], max_length=20),
        ),
    ]
