# Generated by Django 4.1.5 on 2023-02-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_order_qr_pointer_alter_batch_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='qrcode_path',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='qrcode_url',
        ),
        migrations.AddField(
            model_name='batch',
            name='qr_pointer',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='batch_qr_codes'),
        ),
    ]
