# Generated by Django 4.1.6 on 2023-08-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_label_brand_alter_container_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.product'),
        ),
    ]
