# Generated by Django 4.1.6 on 2023-08-26 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_customerorderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honeystock',
            name='nova_ibc',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='ibc_identification',
        ),
        migrations.AddField(
            model_name='honeystock',
            name='ibc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IBC'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='previous_batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parent_batch', to='home.batch'),
        ),
        migrations.AlterField(
            model_name='container',
            name='color',
            field=models.CharField(choices=[('Clear', 'Clear'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Dark Brown', 'Dark Brown'), ('White', 'White'), ('Blue', 'Blue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lid',
            name='color',
            field=models.CharField(choices=[('Clear', 'Clear'), ('Yellow', 'Yellow'), ('Black', 'Black'), ('Dark Brown', 'Dark Brown'), ('White', 'White'), ('Blue', 'Blue')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lid',
            name='type',
            field=models.CharField(choices=[('Jar Lid', 'Jar Lid'), ('Squeeze Lid', 'Squeeze Lid'), ('Squeeze Tip', 'Squeeze Tip'), ('Tub Lid', 'Tub Lid'), ('Pail Lid', 'Pail Lid')], max_length=20),
        ),
    ]
