# Generated by Django 4.1.6 on 2023-08-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_honeystock_nova_ibc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='honeystock',
            old_name='ibc',
            new_name='ibc_number',
        ),
    ]
