# Generated by Django 4.1.6 on 2023-08-29 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_ibc_honeystock_ibc_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pallet',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='production',
            name='pallet',
        ),
        migrations.RemoveField(
            model_name='production',
            name='top_insert',
        ),
        migrations.AddField(
            model_name='product',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.pallet'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_insert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.topinsert'),
        ),
    ]
