# Generated by Django 4.1.6 on 2023-08-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_pallet_customer_remove_production_pallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
