# Generated by Django 4.1.6 on 2023-08-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_alter_supplierorder_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
