# Generated by Django 4.1.6 on 2023-08-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_supplierorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='payment_due_date',
            field=models.DateField(null=True),
        ),
    ]
