# Generated by Django 4.1.6 on 2023-09-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_supplierorder_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='honey_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='tank_number',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
