# Generated by Django 4.1.6 on 2023-09-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_batch_honey_type_alter_batch_tank_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='produced_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
