# Generated by Django 4.1.6 on 2023-09-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_production_production_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pallet',
            old_name='pallet_name',
            new_name='name',
        ),
    ]
