# Generated by Django 4.1.6 on 2023-10-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_topinsert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
