# Generated by Django 4.1.6 on 2023-10-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_config_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cartons_per_layer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='cartons_per_pallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='layers_per_pallet',
            field=models.IntegerField(default=0),
        ),
    ]
